pull_request_rules:
  - name: Automatic merge for Dependency pull requests
    conditions:
      - label=dependencies
      - check-success=Analyze (javascript)
      - check-success=Run Unit Tests
      - check-success=Lint
      - check-success=Typecheck
      - check-success=Test Build
    actions:
      merge:
        method: rebase
