title: Lydia Michelle
author:
  name: Marisa Clardy
  copyright: © 2020
  website: https://clardy.eu
description: >-
  Hi, my name is Lydia. I am a self-taught artist from Texas.
  I work in many different mediums, including pen and ink, oil, acrylics,
  clay sculpture and ceramics. My ambitions include going to university to get
  a degree in the fine arts and education. I hope to one day become a professor
  where I can give others the reigns to the artistic experience. I also wish
  to use the arts as a way to give relief and therapy for others whom have
  suffered great trauma such as domestic and sexual abuse survivors.
  My current projects are my illustrative art series Greenly , and an upcoming
  novel intended as art therapy for sexual assault survivors.
baseurl: ""
url: "https://lydiamichelle.com"

social:
  github:  lydiamichelleb
  instagram: squid.lyds

plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-purgecss
