on: pull_request
name: Test

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn
      - name: Run Tests
        run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn
      - name: Run Lint
        run: yarn lint:ci

  types:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn
      - name: Run Type Check
        run: yarn lint:types

  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-
      - name: Install Modules
        run: yarn
      - name: Run build
        run: yarn build
